# https://docs.github.com/zh/actions
name: blog sync

on:
  workflow_dispatch: # 启用手动触发工作流
  push:
    branches:
      - master
  pull_request:


permissions: # 操作权限
  contents: read
  pull-requests: read


jobs:
  sync-repository: # 同步文件到其他库
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout notes-docsify repo
        uses: actions/checkout@v3
        with:
          repository: bajins/notes-docsify
          path: notes-docsify
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Sync
        run: |
          find notes-docsify -maxdepth 1 -printf '%P\n' \
            | grep -Ev ".git.*|.nojekyll|CNAME|README.*|index.*|push.*|wercker.*" \
            | xargs rm -rf
          cp -r \
            Go IDE Java Other Python Shell SQL System Web .vuepress/public/images .vuepress/public/files \
            notes-docsify
          cd notes-docsify
          chmod +x .git/hooks/pre-commit
          echo -e '#!/bin/bash\n\n./push.sh'>.git/hooks/pre-commit
          git add -A
          git commit -m "update"
          git push
      
      - name: Gather files changed
        uses: trilom/file-changes-action@1.2.4
        with:
          output: 'json'
          fileOutput: 'json'

      - name: Show files changed
        run: cat $HOME/files.json