name: blog deploy

on:
  push:
    branches:
      - master

jobs:
  sync-repository: # 同步文件到其他库
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout notes-docsify repo
        uses: actions/checkout@v3
        with:
          repository: bajins/notes-docsify
          path: notes-docsify
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Sync
        run: |
          find notes-docsify -maxdepth 1 -printf '%P\n' \
            | grep -Ev ".git.*|.nojekyll|CNAME|README.*|index.*|push.*|wercker.*" \
            | xargs rm -rf
          cp -r \
            Go IDE Java Other Python Shell SQL System Web .vuepress/public/images .vuepress/public/files \
            notes-docsify
          cd notes-docsify
          chmod +x .git/hooks/pre-commit
          echo -e '#!/bin/bash\n\n./push.sh'>.git/hooks/pre-commit
          git add -A
          git commit -m "update"
          git push